name: Xcode - Build Analyze Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: 0 0 * * * #trigger once a day, according to the cron syntax

jobs:
  build:
    name: Build and analyze and test using xcodebuild command
    runs-on: macos-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Xcode 
      uses: axmolengine/setup-xcode@v1.5.2
      # with:
      #   xcode-version: '15'

    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme "Athlete Zone Tests"

    - name: Build and test
      # run: xcodebuild test -scheme "Athlete Zone Tests" -destination 'platform=iOS Simulator,name=iPhone 14,OS=16'
      uses: sergeysova/xcodebuild-action@v2.1.0
      with:
        # project: AthleteZone
        project: Work/Athlete Zone/Athlete Zone/AthleteZone/Athlete Zone
        scheme: "Athlete Zone Tests"
        action: test
      
            
