name: Xcode - Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: 0 0 * * * #trigger once a day, according to the cron syntax

jobs:
  build:
    name: Build and analyze and test using xcodebuild command
    runs-on: macos-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Xcode 
      uses: axmolengine/setup-xcode@v1.5.2
      # with:
      #   xcode-version: '14.2.0'

    # - name: Show eligible build destinations
    #   run: xcodebuild -showdestinations -scheme "Athlete Zone Tests"

    - name: Build and test
      # run: xcodebuild test -scheme "Athlete Zone Tests" -sdk iphonesimulator -destination 'platform=iOS,OS=17.0.1,name=iPhone 15'
      run: xcodebuild test-without-building \
        -derivedDataPath "derivedData" \
        -project "Athlete Zone.xcodeproj" \
        -scheme "Athlete Zone Tests" \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,OS=13.5,name=iPhone SE (2nd generation)' \
        -enableCodeCoverage YES
      
