name: Xcode - Build Analyze Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyze and test using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          xcodebuild clean test -workspace "Athlete Zone.xcworkspace" -scheme "Athlete Zone" -destination "platform=iOS Simulator,OS=16.0,name=iPhone 14"