name: Xcode - Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: 0 0 * * * #trigger once a day, according to the cron syntax

jobs:
    build:
      strategy:
        matrix:
          platform:
            - iOS
          xcode:
            - ^15
      runs-on: macos-latest
      steps:
        - uses: mxcl/xcodebuild@v1
          with:
            xcode: ${{ matrix.xcode }}
            platform: ${{ matrix.platform }}
            configuration: release
            scheme: "Athlete Zone Tests"
