name: Xcode - Build Analyze Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and analyze and test using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        run: sudo Xcode-select -switch /Applications/Xcode_13.2.1.app

      - name: Build and Test
        run: |
          xcodebuild clean build test -workspace "AthleteZone.xcworkspace" -scheme "Athlete Zone Tests" -destination "platform=iOS Simulator,name=iPhone 13,OS=16"