name: Xcode - Build Analyze Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyze and test using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test
        run: |
          xcodebuild clean test -workspace "AthleteZone.xcworkspace" -scheme "Athlete ZoneTests" -destination "platform=iOS Simulator,name=iPhone 11"
