name: Xcode - Build Analyze Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 0 * * * #trigger once a day, according to the cron syntax

jobs:
  build:
    name: Build and analyze and test using xcodebuild command
    runs-on: macos-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Xcode 
      uses: axmolengine/setup-xcode@v1.5.2

    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme "Athlete Zone Tests"

    - name: Build and test ( iOS 17.0)
      run: xcodebuild test -scheme "Athlete Zone Tests" -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 15'
        
        
        # run: |
        #  xcodebuild clean build test -workspace "AthleteZone.xcworkspace" -scheme "Athlete Zone Tests" -destination "platform=iOS Simulator,name=iPhone 13,OS=16"
