name: Xcode - Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: 0 0 * * * #trigger once a day, according to the cron syntax

jobs:
  build:
    name: Build and analyze and test using xcodebuild command
    runs-on: macos-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Xcode 
      uses: axmolengine/setup-xcode@v1.5.2
      with:
        xcode-version: '14.2.0'

    - name: install simulator
      run: xcversion simulators --install='iOS 15.4'

    - name: Prepare iOS 15.4 simulator
      run: |
        sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
        sudo ln -s /Applications/Xcode_14.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 15.4.simruntime
        xcrun simctl list runtimes
        xcrun simctl create iPhone_14 "iPhone 14" "com.apple.CoreSimulator.SimRuntime.iOS-15-4"
        xcrun simctl list devices 15.4
      
    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme "Athlete Zone Tests"

    - name: Build and test
      run: xcodebuild test -scheme "Athlete Zone Tests" -sdk iphonesimulator -destination 'platform=iOS,name=iPhone 15'
      
